### ISSUE TITLE
PoisonError panic

### ISSUE THREAD

**Issue by Niedzwiedzw** [emersonford/tracing-indicatif#14]
wnquestbug__000B8C96_1.fuz", "sound/voice/arnima.esm/ArnimaLutherVoice/ArnimaOrcM_ArnimaOrcMainqu_0013DC54_1.fuz"]}thread '<unnamed>' panicked at /home/niedzwiedz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/indicatif-0.17.9/src/multi.rs:140:62:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at /home/niedzwiedz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-indicatif-0.3.8/src/lib.rs:681:58:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
stack backtrace:
   0:     0x5653e9e5c55a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h95a44616294b6072
   1:     0x5653e9e8a553 - core::fmt::write::h71f0d7be5c15b0df
   2:     0x5653e9e57353 - std::io::Write::write_fmt::h0d5595524709c1d7
   3:     0x5653e9e5c3a2 - std::sys::backtrace::BacktraceLock::print::hf1c6b1b3b7f8011d
   4:     0x5653e9e5d4ac - std::panicking::default_hook::{{closure}}::h060219f22b106201
   5:     0x5653e9e5d2f2 - std::panicking::default_hook::h45366c603bf9ceca
   6:     0x5653e9e5dae7 - std::panicking::rust_panic_with_hook::h04c182b84bcc3d04
   7:     0x5653e9e5d97a - std::panicking::begin_panic_handler::{{closure}}::h74727f9b5de8304b
   8:     0x5653e9e5ca39 - std::sys::backtrace::__rust_end_short_backtrace::h1c1c1acffbdf4e8d
   9:     0x5653e9e5d60c - rust_begin_unwind
  10:     0x5653e9e875c0 - core::panicking::panic_fmt::he0c258f1303ba031
  11:     0x5653e9e87a06 - core::result::unwrap_failed::hbe6100fa2aeaf22b
  12:     0x5653e95a1030 - <tracing_subscriber::layer::layered::Layered<L,S> as tracing_core::subscriber::Subscriber>::try_close::h6b15eb2fef7d2f65
  13:     0x5653e9be4226 - <tracing_subscriber::registry::sharded::DataInner as sharded_slab::clear::Clear>::clear::h7f1e3d7c2ea567bf
  14:     0x5653e9bdf51d - sharded_slab::page::slot::Slot<T,C>::release_with::hed3a71f417843f71
  15:     0x5653e95a10ea - <tracing_subscriber::layer::layered::Layered<L,S> as tracing_core::subscriber::Subscriber>::try_close::h6b15eb2fef7d2f65
  16:     0x5653e964693a - <hoolamike::compression::compress_tools::ArchiveHandle as hoolamike::compression::ProcessArchive>::get_many_handles::h676d6025f6a1900d
  17:     0x5653e96c8769 - <hoolamike::compression::ArchiveHandle as hoolamike::compression::ProcessArchive>::get_many_handles::h8c50209d9ac4d2a2
  18:     0x5653e966e024 - tracing::span::Span::in_scope::h2d96c02b611878cd
  19:     0x5653e96ab949 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::h3eeb6335c551b7aa
  20:     0x5653e972aa67 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold::hc4d027a42d8bb137
  21:     0x5653e95c3e0d - <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next::h93be041fb621efdd
  22:     0x5653e979a6c7 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h2065e34f70c63c5c
  23:     0x5653e95cf0c1 - core::iter::adapters::try_process::h863c359895a383b1
  24:     0x5653e966c809 - tracing::span::Span::in_scope::h079788efe3f1ad56
  25:     0x5653e96abe03 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::hf1c00bb38dea28fd
  26:     0x5653e97924bb - rayon::iter::plumbing::Folder::consume_iter::h2169ae56ea580350
  27:     0x5653e96ef6e3 - rayon::iter::plumbing::bridge_producer_consumer::helper::hd0665c699e7f1cc9
  28:     0x5653e97b6297 - rayon_core::join::join_context::{{closure}}::h6390f207a8a7c791
  29:     0x5653e97b8635 - rayon_core::registry::in_worker::h0299bd5a0027ffd4
  30:     0x5653e96ef82f - rayon::iter::plumbing::bridge_producer_consumer::helper::hd0665c699e7f1cc9
  31:     0x5653e97b6297 - rayon_core::join::join_context::{{closure}}::h6390f207a8a7c791
  32:     0x5653e97b8635 - rayon_core::registry::in_worker::h0299bd5a0027ffd4
  33:     0x5653e96ef82f - rayon::iter::plumbing::bridge_producer_consumer::helper::hd0665c699e7f1cc9
  34:     0x5653e97b6297 - rayon_core::join::join_context::{{closure}}::h6390f207a8a7c791
  35:     0x5653e97b8635 - rayon_core::registry::in_worker::h0299bd5a0027ffd4
  36:     0x5653e96ef82f - rayon::iter::plumbing::bridge_producer_consumer::helper::hd0665c699e7f1cc9
  37:     0x5653e97db10c - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h997ffe739619a82e
  38:     0x5653e9c484c2 - rayon_core::registry::WorkerThread::wait_until_cold::h5ec4a8c1051d4682
  39:     0x5653e9c465fb - rayon_core::registry::ThreadBuilder::run::h351b3b2f51d86fc2
  40:     0x5653e9c4878a - std::sys::backtrace::__rust_begin_short_backtrace::h489fec643bf72ab2
  41:     0x5653e9c4c02a - core::ops::function::FnOnce::call_once{{vtable.shim}}::h9613fdf937960571
  42:     0x5653e9e6282b - std::sys::pal::unix::thread::Thread::new::thread_start::h18940518fc80e0fb
  43:     0x7f0fa08e1d02 - start_thread
  44:     0x7f0fa09613ac - __GI___clone3
  45:                0x0 - <unknown>
thread '<unnamed>' panicked at core/src/panicking.rs:231:5:
panic in a destructor during cleanup
thread caused non-unwinding panic. aborting.
thread '<unnamed>' panicked at /home/niedzwiedz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-indicatif-0.3.8/src/lib.rs:681:58:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
fish: Job 1, 'cargo run --release -- install …' terminated by signal SIGABRT (Abort)

**Comment by emersonford** [comment]
I'm able to reproduce this with:
```
#[test]
fn test_parent_span_enter_ordering() {
    let (subscriber, _) = make_helpers(HelpersConfig::default());

    tracing::subscriber::with_default(subscriber, || {
        let grandparent_span = info_span!("grandparent");
        let parent_span = info_span!(parent: &grandparent_span, "parent");
        let child_span = info_span!(parent: &parent_span, "child");

        let span1 = info_span!("span1");
        span1.pb_start();
        let span2 = info_span!("span2");
        span2.pb_start();
        let span3 = info_span!("span3");
        span3.pb_start();
        let span4 = info_span!("span4");
        span4.pb_start();
        let span5 = info_span!("span5");
        span5.pb_start();

        child_span.pb_start();
        grandparent_span.pb_start();

        drop(span1);
    });
}
```

which appears to be because of this line: https://github.com/emersonford/tracing-indicatif/blob/ee591760d1bcf52d7459facf1dc43ec93dcdff59/src/lib.rs#L669

certainly wasn't expecting anyone to have this particular span enter order, but will think of a fix for it.

**Comment by emersonford** [comment]
should be fixed with https://github.com/emersonford/tracing-indicatif/commit/2ccd6df644594bc84015c71649ef3f5f93e438d9, let me know if you continue to see this issue. thanks for the report!

**Comment by Niedzwiedzw** [comment]
still happening sadly

**Comment by Niedzwiedzw** [comment]
couldnt we just log an error when this is happening instead of unwrapping? like - this is a progress bar library, if its broken then well too bad bad crashing the entire program is not good I think. Also couldn't we use parking_lot mutex which will never throw a poison error in the first place?
